gongjakso/package-lock.json, gongjakso/package.json, gongjakso/src/components/Header/Header.Styled.jsx, gongjakso/src/components/Header/Header.jsx, gongjakso/src/hooks/useNavigate.js, gongjakso/yarn.lock
1. 헤더 UI 구현
1. 헤더 항목 클릭 시 잘 작동되는지 확인해주세요
2. 헤더 UI가 유사한지 확인해주세요
Issue Number:  #10
=> 🔀 Feat/headerUI#10 [UI]

gongjakso/src/components/Footer/Footer.Styled.jsx, gongjakso/src/components/Footer/Footer.jsx
1. 푸터 UI 구현
1. 푸터 UI가 유사한지 확인해주세요
Issue Number:  #11
=> 🔀 Feat/footerUI#11 [UI]

gongjakso/src/Layout/DefaultLayout.styled.jsx, gongjakso/src/components/Footer/Footer.Styled.jsx, gongjakso/src/components/Footer/Footer.jsx, gongjakso/src/components/Header/Buttons.jsx, gongjakso/src/components/Header/Buttons.styled.jsx, gongjakso/src/components/Header/Header.Styled.jsx, gongjakso/src/components/Header/Header.jsx, gongjakso/src/hooks/useNavigate.js, gongjakso/src/styles/GlobalStyle.js
1. 전체적인 레이아웃 틀 수정 고정적으로 변할수 있도록
2. 헤더와 푸터 수정
1. 헤더 푸터가 잘 보이는지 확인해주세요
2. 페이지 전환이 잘 되는지 확인해주세요
3. 헤더 부분에 해당 페이지가 어떤 페이지 인지 색표시가 잘 되는지 확인해주세요
아래 코드를 라우터에 추가한 후 확인해주세요!
```
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import PublicRoutePage from './PublicRoute';
import PrivateRoutePage from './PrivateRoute';
import { Suspense } from 'react';
import HomePage from '../pages/HomePage/HomePage';
import DefaultLayout from '../Layout/DefaultLayout';
import ProfilePage from '../pages/ProfilePage/ProfilePage';
import TeamPart from '../pages/ProfileParticipated/ParticipatedTeam';
import TeamSupport from '../pages/ProfileApplied/AppliedTeam';
import TeamPortfolio from '../pages/Portfolio/MyPortfolio';
import Calendar from '../pages/CalendarPage/Calendar';
const Router = () => { …
```
=> 🔀 Fix/edit layout#16 [UI Layout]

gongjakso/src/features/modal/LoginModal1.jsx, gongjakso/src/features/modal/LoginModal2.jsx, gongjakso/src/features/modal/Modal.Styled.jsx, gongjakso/src/pages/HomePage/HomePage.jsx, gongjakso/src/pages/HomePage/HomePageStyled.jsx
1. 로그인 모달 UI 구현
2. 홈페이지의 버튼 클릭 시 페이지에 적합한 모달 띄우기 처리
3. 모달의 버튼 클릭 시 각 페이지로 이동 처리
1. 홈페이지의 버튼 클릭 시 모달이 잘 실행되는지
4. 프로젝트, 공모전의 버튼 클릭 시 로그인 모달 2가 실행되는지
5. 팀빌딩, 캘린더 버튼 클릭 시 로그인 모달 1이 실행되는지
6. 모달의 로그인 버튼 클릭 시 로그인 페이지로 잘 이동하는지
7. 모달의 로그인하지 않고 둘러보기 버튼 클릭 시 각 페이지로 잘 이동하는지
8. 디자인이 유사한지 확인부탁드려요
Issue Number:  #17
=> 🔀 Feat/login modal UI#17 [UI]

gongjakso/src/features/modal/ApplyModal.jsx, gongjakso/src/features/modal/ApplyModal.styled.jsx, gongjakso/src/features/modal/Completed.jsx, gongjakso/src/features/modal/Roundform.jsx, gongjakso/src/pages/DetailPage/DetailPageContest.jsx, gongjakso/src/pages/DetailPage/DetailPageProject.jsx
1. 공고 상세페이지에서 지원하기 버튼 눌렀을 때 나오는 모달창 구현
2. 지원하기 모달창 기능 구현 - 지원 분야 선택 및 지원 이유 작성란
3. 모달 속 지원하기 버튼 눌렀을 때 나오는 지원완료 모달창 구현
4. 지원완료 모달창 기능 구현 - x 버튼 누르면 공고 페이지 이동 및 마이페이지 버튼 누르면 이동 
5. **프로젝트 공고 모달창에서는 해당 공고 페이지에 기재된 기술 스택 부분을 넣어서 작업하였습니다 (추후 논의 사항)**
1. 확인할 때는 **공모전과 프로젝트 각각의 모달창**을 다 확인해주세요
2. 확인 시 **1940 모니터 크기**로 봐주세요!! 
3. 공모전과 프로젝트 모달창 타이틀이 각각 올바르게 나오는지 확인해주세요
4. 지원하기 버튼 눌렀을 때 모달창이 잘 나오는지 확인해주세요
5. 지원 분야 부분에서 분야 클릭 시 색깔이 잘 변하는지, 중복 선택이 되지는 않는지 확인해주세요
6. **프로젝트 공고 지원하기 모달창**에서는 기술 스택 부분이 추가로 보이는지, 클릭 시 색깔이 잘 변하는지 **중복 선택이 잘 되는지** 확인해주세요
7. 지원 이유 부분에서 입력칸이 잘 늘어나는지 500자 제한이 잘 걸려 있고 입력칸의 글자수가 잘 표시되는지 확인해주세요
8. 지원하기 버튼을 누르면 지원 완료 모달창이 잘 뜨는지 확인해주세요
9. 지원 완료 모달창에서 x 버튼을 누르면 링크가 잘 이동하는지, 마이페이지 버튼 누르면 마이페이지로 잘 이동하는지 확인해주세요
아래 코드를 라우터에 추가한 후 확인해주세요!
```
import { BrowserRouter, Routes, Route } from …
```
=> 🔀 Feat/applyPageUI#21 [UI] 

gongjakso/.gitignore, gongjakso/src/components/Auth/KakaoRedirectPage.Styled.jsx, gongjakso/src/components/Auth/KakaoRedirectPage.jsx, gongjakso/src/components/Auth/Login.Styled.jsx, gongjakso/src/components/Auth/Login.jsx, gongjakso/src/router/Router.jsx
1. 메인페이지의 모달 내 버튼 클릭 시 로그인 페이지로 넘어가도록 처리
2. 로그인 페이지 디자인 유사하게 조정
3. 카카오 로그인 버튼 눌렀을 때 처리
1. 모달 내 버튼 클릭 시 로그인 페이지로 잘 넘어가는지 확인 부탁드려요
2. 전체적으로 디자인과 유사한지 확인 부탁드려요
3. 카카오 로그인 버튼 클릭 시 로그인 과정으로 잘 넘어가는지 확인 부탁드려요
4. 로그인 과정을 거치면 redirect되는 페이지에서 원 형태 스피너가 잘 돌아가는지 확인 부탁드려요 
Issue Number:  #23
=> 🔀 Feat/loginPageUI#23

gongjakso/src/pages/HomePage/Banner.Styled.jsx, gongjakso/src/pages/HomePage/Banner.jsx, gongjakso/src/pages/HomePage/HomePage.Styled.jsx, gongjakso/src/pages/HomePage/HomePage.jsx
1. 메인 페이지에 배너 구현
1. 메인 페이지에서 배너가 잘 작동하는지 확인 부탁드려요
2. 현재는 색상으로 대체되었지만 틀이 디자인과 유사한지 확인 부탁드려요
Issue Number:  #37
=> 🔀 Feat/mainPageBannerUI#37

gongjakso/src/pages/ProfileParticipated/ParticipatedTeam.jsx, gongjakso/src/pages/ProfileParticipated/ParticipatedTeamStyled.jsx
1. 기존 만들어둔 teamBox 불러옴
1. '마이페이지-내가 참여한 공모전/프로젝트'에 나와있는 리스트와 동일한 정보가 페이지에 담겨있는지 확인해주세요.
2. 해당 페이지의 헤더부분 배경색이 뒤로 가도록 수정이 필요할 것 같습니다.
Router.jsx
```
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import PublicRoutePage from './PublicRoute';
import PrivateRoutePage from './PrivateRoute';
import { Suspense } from 'react';
import HomePage from '../pages/HomePage/HomePage';
import DefaultLayout from '../Layout/DefaultLayout';
import ProfilePage from '../pages/ProfilePage/ProfilePage';
import TeamPart from '../pages/ProfileParticipated/ParticipatedTeam';
import TeamSupport from '../pages/ProfileApplied/AppliedTeam';
import TeamPortfolio from '../pages/Portfolio/MyPortfolio';
import Calendar from '../pages/CalendarPage/Calendar';
import DetailPageContest from …
```
=> 🔀 Feat/profileParticipatedTeamUI#40

gongjakso/package-lock.json, gongjakso/package.json, gongjakso/src/assets/images/banner.svg, gongjakso/src/components/Header/Buttons.jsx, gongjakso/src/components/Pagination/Pagination.jsx, gongjakso/src/components/SwiperBanner/SwiperBanner.Styled.jsx, gongjakso/src/components/SwiperBanner/SwiperBanner.jsx, gongjakso/src/components/common/Input/Input.Styled.jsx, gongjakso/src/components/common/Input/Input.jsx, gongjakso/src/pages/PostMainPage/PostMainPage.Styled.jsx, gongjakso/src/pages/PostMainPage/PostMainPage.jsx, gongjakso/src/router/Router.jsx, gongjakso/yarn.lock
1. 프로젝트/공모전 공고 페이지 구현
2. 게시물 갯수에 따른 페이지 네이션 구현
3. input, selectInput 수정
4. 배너 구현
1. 프로젝트/공모전 공고 페이지에 따른 레이아웃이 다른지 확인해주세요
2. 게시물 갯수에 맞게 페이지 네이션이 잘 작동하는지 확인 해주세요
3. input, selectInput이 깔끔하게 수정 되었는지 확인 해주세요
4. 배너가 잘 작동하는 지 확인 해주세요
1. npm install swiper -> 다운 받아주세요
2. 아래 router.jsx 코드를 넣고 실행해 주세요
```
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import PublicRoutePage from './PublicRoute';
import PrivateRoutePage from './PrivateRoute';
import { Suspense } from 'react';
import HomePage from '../pages/HomePage/HomePage';
import DefaultLayout from '../Layout/DefaultLayout';
import ProfilePage from '../pages/ProfilePage/ProfilePage';
import TeamPart from '../pages/ProfileParticipated/ParticipatedTeam';
import TeamSupport from '../pages/ProfileApplied/AppliedTeam';
import …
```
=> 🔀Feat/postPageUI#43 [UI]

gongjakso/src/pages/Portfolio/MyPortfolio.jsx, gongjakso/src/pages/Portfolio/MyPortfolioStyled.jsx, gongjakso/src/pages/ProfileApplied/AppliedTeam.jsx, gongjakso/src/pages/ProfileApplied/AppliedTeamStyled.jsx, gongjakso/src/pages/ProfilePage/ProfilePage.jsx, gongjakso/src/pages/ProfilePage/ProfilePageStyled.jsx, gongjakso/src/pages/ProfileParticipated/ParticipatedTeam.jsx, gongjakso/src/pages/ProfileParticipated/ParticipatedTeamStyled.jsx, gongjakso/src/pages/TeamBox/TeamBox.jsx, gongjakso/src/pages/TeamBox/TeamBoxStyled.jsx
1. 프로필 홈 페이지 글자 크기/간격 변경
2. 프로필 홈 페이지 기존 TopButton 지운 후 Homepage에 있는 것 가져옴 (높이 1200 초과 시 보이기 때문에 현재는 안보임)
3. teamBox 전체적인 레이아웃 수정
4. teamBox '내가 모집 중인 팀'의 경우 박스 내 화살표 표시 있는 부분만 margin 더 적용됨
피그마와 전체적인 글자크기, 레이아웃이 비슷하게 구현되었는지 봐주세요 (프로필 홈페이지, 내가 지원한 팀 페이지, 내가 참여한 공모전/프로젝트 페이지)
Issue Number:  #53
=> 🔀 Fix/profilePageUI#53

gongjakso/src/pages/HomePage/HomePage.Styled.jsx, gongjakso/src/styles/theme.js
1. theme.js를 이용해 스타일 파일에서 폰트 색상 및 크기 수정
2. Globalstyle.js를 이용해 스타일 파일에서 폰트 종류 수정
3. 전체적인 레이아웃 수정
1. 메인페이지 화면이 디자인과 유사한지 확인해주세요
2. homepage.styled.jsx 파일에서 스타일 적용 방식이 제대로 되었는지 확인해주세요
Issue Number:  #55
=> 🔀 Fix/editMainPageUI#55

gongjakso/src/features/modal/ClickApply.jsx, gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx, gongjakso/src/pages/ProfileRecruit/ProfileRecruit.styled.jsx, gongjakso/src/pages/ProfileRecruit/UserData.jsx
1. 전체적인 레이아웃 보완
2. 헤더와의 겹침 부분 수정
3. 폰트 크기 수정
4. 마이페이지와의 파란 박스 넓이 통일
5. 프로젝트의 경우 지원서 보기 모달에 기술 스택 부분 추가
1. 전체적인 레이아웃이 잘 적용되었는지 확인 부탁드려요
2. 헤더가 앞으로 잘 나와있는지 확인 부탁드려요
3. 지원서 보기를 눌렀을 때 기술스택 부분이 잘 나오는지 확인 부탁드려요
Issue Number:  #54
=> 🔀 Fix/editProfileRecruitUI#54 [UI 수정]

gongjakso/src/pages/CalendarPage/Calendar.jsx, gongjakso/src/pages/CalendarPage/Calendar.styled.jsx, gongjakso/src/pages/CalendarPage/data/contestData.js, gongjakso/src/pages/CalendarPage/data/projectData.js, gongjakso/src/pages/DetailPage/DetailPageContest.jsx, gongjakso/src/pages/DetailPage/DetailPageProject.jsx, gongjakso/src/pages/DetailPage/DetailPageStyled.jsx
1. 캘린더 UI 수정
2. 공고 상세페이지 스크랩 횟수 박스 UI 수정
1. 최종 수정된 캘린더 UI가 피그마 디자인과 유사한지 확인부탁드려요
2. 공고 상세페이지 스크랩 횟수 표시되는 박스가 마이페이지 스크랩과 유사한지 확인부탁드려요
Issue Number:  #61
=> 🔀 Fix/editPagesStyle#61 [UI] 수정

gongjakso/src/components/Header/Buttons.jsx, gongjakso/src/features/modal/LoginModal1.jsx, gongjakso/src/features/modal/LoginModal2.jsx, gongjakso/src/pages/HomePage/HomePage.Styled.jsx, gongjakso/src/pages/HomePage/HomePage.jsx, gongjakso/src/pages/PostMainPage/PostMainPage.jsx, gongjakso/src/service/axiosInstance.js, gongjakso/src/service/banner_service.js
1. 로그인 유무의 따른 헤더 클릭 시 발생하는 모달 작업
2. axios를 사용하여 동작할 수 있게 api 기초 세팅
1. 로그인을 안한 상태에서 헤더를 클릭했을 때, 프로젝트/공모전 공고에서는 로그인 안하고 둘러보기가 보이고, 캘린더 팀빌딩에서는 로근인하기 모달이 보이는지 확인해주세요
2. 헤더가 잘 동작하는지 확인 해주세요
Issue Number:  #67
=> 🔀 Feat/editLoginApi#67 [API] api 세팅 및 로그인 유무의 따른 헤더 작업

gongjakso/src/features/modal/LoginModal1.jsx, gongjakso/src/features/modal/LoginModal2.jsx, gongjakso/src/features/modal/Modal.Styled.jsx, gongjakso/src/features/modal/SignUpModal.jsx, gongjakso/src/pages/HomePage/HomePage.jsx
1. 로그인, 회원가입 관련 모달 스타일 수정
2. 회원가입 모달에 드롭다운 추가
3. 간편 로그인 후 첫 로그인 시 회원가입 모달 띄우기
1. 로그인 모달1, 2, 회원가입 모달의 디자인이 잘 적용되었는지 확인 부탁드려요
2. 처음으로 회원가입 후 로그인을 했을 경우 화면에 회원가입 모달이 나타나는지 확인 부탁드려요
Issue Number:  #58
=> 🔀 Fix/EditLoginModalUI#58

gongjakso/src/components/Footer/Footer.jsx
1. 푸터 이용약관 버튼 링크 연결
2. 푸터 개인정보처리방침 버튼 링크 연결
1. 푸터 이용약관 버튼 눌렀을 때 새로운 창에 pdf가 뜨는지 확인 부탁드려요
2. 푸터 개인정보처리방침 버튼을 눌렀을 때 새로운 창에 pdf가 뜨는지 확인 부탁드려요
Issue Number:  #74
=> 🔀 Feat/FooterLink#74

gongjakso/src/components/Header/Buttons.jsx, gongjakso/src/components/SwiperBanner/SwiperBanner.Styled.jsx, gongjakso/src/components/SwiperBanner/SwiperBanner.jsx, gongjakso/src/pages/PostMainPage/PostMainPage.jsx
1. 메인 페이지 배너부분 api 추가하여 배너 띄우기
1. 메인 페이지 공고 부분에 배너가 잘 보이는 지 확인해주세요
Issue Number:  #79
=> 🔀 Feat/editMainPageBannerApi#79 [API] 구현

gongjakso/src/components/common/Calendar/SelectCalendar.Styled.jsx, gongjakso/src/features/modal/ApplyModal.styled.jsx, gongjakso/src/features/modal/MyPageTeam.jsx, gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx, gongjakso/src/service/apply_service.js
1. 마감 연장 모달에 달력 추가
2. api를 연결하여 post_id 를 받으면 해당하는 post에 마감 기한을 연장 한다.
1. 마감 연장 모달에 달력이 잘 보이는지 확인 해주세요
Issue Number:  #82
=> 🔀Feat/addExtendCalendar#82 [API] 마감연장 달력 추가

gongjakso/src/components/common/Calendar/SelectCalendar.Styled.jsx, gongjakso/src/components/common/CountGuest/CountGuest.Styled.jsx, gongjakso/src/components/common/Input/Input.Styled.jsx, gongjakso/src/components/common/Input/Input.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.Styled.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.jsx, gongjakso/src/service/post_service.js
1. 게시물 올릴 수 있게 post API 연결
1. 올린 게시물의 데이터가 잘 저장 되는지 확인해주세요
Issue Number:  #86
=> 🔀Feat/postTeamBuildingApi#86 [API]

gongjakso/src/features/modal/ApplyModal.jsx, gongjakso/src/features/modal/ApplyModal.styled.jsx, gongjakso/src/features/modal/ClickApply.jsx, gongjakso/src/features/modal/Completed.jsx, gongjakso/src/features/modal/MyPageTeam.jsx, gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx, gongjakso/src/pages/ProfileRecruit/ProfileRecruit.styled.jsx, gongjakso/src/service/apply_service.js
1. 내가 모집중인 팀 상단 파란 박스 및 버튼 api 연결 완료
2. 내가 모집중인 팀 지원자 현황 api 연결 완료
3. 모달창 박스 크기 조정
4. 모달창 스크롤바 고정 기능 추가
1. 내가 모집중인 팀 상단 박스 api 연결이 잘 되었는지 확인해주세요
2. 모달창 스크롤 여부 확인해주세요
Issue Number:  #78
=> 🔀 Feat/RecruitBtnAPI#78 [API]

gongjakso/src/features/modal/ApplyModal.jsx, gongjakso/src/pages/DetailPage/DetailPageContest.jsx, gongjakso/src/pages/DetailPage/DetailPageData.jsx, gongjakso/src/pages/DetailPage/DetailPageProject.jsx, gongjakso/src/pages/DetailPage/DetailPageStyled.jsx, gongjakso/src/service/post_service.js
1. 공고 상세페이지 GET API 연결 완료
2. 공고 상세페이지 지원하기 모달창 버튼 POST API 연결 완료
3. 스크랩 버튼 연결 미완 => 추후 백엔드분께 요청 사항 건의 후 수정 예정
4. 기존 UserData 파일 삭제
1. 공고 상세페이지에 요소들이 잘 뜨는지 확인해주세요 (콘솔로 확인)
2. 지원하기 모달창에서 지원하기 버튼을 눌렀을 때 POST 내용이 올바르게 적용되었는지 확인해주세요 (콘솔로 확인)
3. 지원 분야를 클릭하지 않고 지원하기 버튼을 눌렀을 때 POST가 되지 않는게 맞는지 확인해주세요 (콘솔로 확인)
Issue Number:  #91
=> 🔀 Feat/PostDetailPageAPI#91 [API]

gongjakso/src/assets/mapData/mapData.jsx, gongjakso/src/components/Pagination/Pagination.jsx, gongjakso/src/components/SwiperBanner/SwiperBanner.jsx, gongjakso/src/components/common/Input/Input.jsx, gongjakso/src/components/common/Input/Multilevel.jsx, gongjakso/src/pages/DetailPage/DetailPageContest.jsx, gongjakso/src/pages/DetailPage/DetailPageProject.jsx, gongjakso/src/pages/HomePage/Banner.jsx, gongjakso/src/pages/PostMainPage/PostMainPage.Styled.jsx, gongjakso/src/pages/PostMainPage/PostMainPage.jsx, gongjakso/src/router/Router.jsx, gongjakso/src/service/banner_service.js, gongjakso/src/service/post_service.js
1. 프로젝트/공모전 -> 최신순/인기순, 미팅지역, 페이지 네이션 별로 구현
2. 메인공고 페이지에서 단일 공고로 연결 작업 
1. 페이지 네이션이 잘 작동하는 지 확인해주세요
2. 단일 게시물로 잘 이동하면서 데이터가 잘 변화하는지 확인해주세요
1. teamBox 수정후 teambox로 대체 되어야 함
2. 검색어 기능 추가해야
Issue Number:  #90
=> 🔀 Feat/addMainPageGetApi#90 [게시물 api]

gongjakso/src/components/Header/Buttons.jsx, gongjakso/src/components/Header/Header.Styled.jsx, gongjakso/src/components/Header/Header.jsx
1. 헤더에 로그인 여부에 따른 로그인 , 로그아웃 버튼 추가
2. 로그인 버튼 클릭 시 로그인 페이지로 이동
3. 로그아웃 버튼일 경우 홈페이지로 새로고침
4. 로그아웃 api 연결
1. 로그인 버튼을 누르면 로그인 페이지로 이동하고 로그아웃으로 문자가 바뀌는지 확인부탁드려요
2. 로그아웃 버튼을 누르면 홈페이지로 이동하면서 로그인으로 문자가 바뀌는지 확인 부탁드려요
3. 로그아웃 버튼을 누르고 홈페이지나 헤더의 다른 버튼을 누르면 로그인 모달이 뜨는지 확인 부탁드려요
Issue Number:  #97
=> 🔀 Fix/HeaderUI#97

gongjakso/src/features/modal/MyPageTeam.jsx, gongjakso/src/pages/DetailPage/DetailPageContest.jsx, gongjakso/src/pages/DetailPage/DetailPageProject.jsx, gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx, gongjakso/src/service/apply_service.js
1. 내가 모집중인 팀 API 오류 수정
2. 기존 endDate 를 finishDate 로 수정 완료 (내가 모집중인 팀 / 공고 상세페이지)
1. 내가 모집중인 팀 페이지에 들어왔을 때 오류가 발생하지 않는지 확인해주세요
2. 내가 모집중인 팀 페이지 상단 박스에 마감하기 버튼을 눌렀을 때 정상 작동되는지 콘솔로 확인해주세요
3. 마감일이 올바르게 나오는지 확인부탁드려요
Issue Number:  #95
=> 🔀 Fix/RecruitAPI#95 [API]

gongjakso/src/pages/DetailPage/DetailPageContest.jsx, gongjakso/src/pages/DetailPage/DetailPageProject.jsx, gongjakso/src/service/post_service.js
1. 스크랩 GET API 연결 완료
2. ScrapStatus 에 따른 스크랩 버튼 스타일 조정 완료
3. 스크랩 버튼 클릭 시, 새로고침되는 코드 추가
1. 스크랩 버튼을 눌렀을 때 새로고침되어 올바르게 스크랩 횟수가 올라가는지, 스크랩 버튼 색상이 변했는지 확인 부탁드려요
2. 다시 한번 `contest/해당id번호`로 들어갔을 때 스크랩 버튼 색상이 올바르게 변해있는지 확인 부탁드려요
Issue Number:  #96
=> 🔀 Feat/AddScrapAPI#96 [API]

gongjakso/src/assets/images/CloseWhite.svg, gongjakso/src/pages/Portfolio/MyPortfolio.jsx, gongjakso/src/pages/Portfolio/MyPortfolioStyled.jsx, gongjakso/src/pages/ProfileApplied/AppliedTeam.jsx, gongjakso/src/pages/ProfileInfo/MyInfo.jsx, gongjakso/src/pages/ProfileInfo/MyInfoStyled.jsx, gongjakso/src/pages/ProfilePage/ProfilePage.jsx, gongjakso/src/pages/ProfilePage/ProfilePageStyled.jsx, gongjakso/src/pages/ProfileParticipated/ParticipatedTeam.jsx, gongjakso/src/pages/TeamBox/TeamBox.jsx, gongjakso/src/pages/TeamBox/TeamBoxStyled.jsx, gongjakso/src/service/profile_service.js
1. 포트폴리오 api 연결
2. 나의 정보에서 수정 시 프로필 메인 페이지에서 정보 반영
3. 내가 모집 중인 팀박스 api 연결
4. 내가 참여한 팀박스 api 연결
1. 포트폴리오 api 연결 (이메일 입력 후 확인 버튼 누르면 콘솔창에 잘 뜨는지 봐주세요./동일한 이메일 주소 입력시 알림창 뜸)
2. 로그인 후 마이페이지에 로그인 시 선택한 전공이 반영되는 지 봐주세요.
3. 나의 정보에서 수정 시 프로필 메인 페이지에서 정보가 반영되는 지 봐주세요.
4. 팀박스 postContent의 데이터 값들을 swagger와 일치하게 반영해두었습니다.
내가 지원한 팀박스 api 연결 부분은 수정 예정입니다.
Issue Number:  #64
=> 🔀Feat/profileApi#64

gongjakso/src/features/modal/ApplyModal.jsx, gongjakso/src/features/modal/ClickApply.jsx, gongjakso/src/pages/CalendarPage/Calendar.jsx, gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx, gongjakso/src/pages/ProfileRecruit/ProfileRecruit.styled.jsx, gongjakso/src/service/apply_service.js, gongjakso/src/service/calendar_service.js
1. 캘린더 API 연결
2. 내가 모집중인 팀 지원자 현황 API 연결
3. 지원서 보기 API 연결
1. API들이 잘 연결되었는지 확인해주세요
Issue Number:  #94
=> 🔀 Feat/CalendarRecruitAPI#94 [API]

gongjakso/src/components/common/Input/Input.Styled.jsx, gongjakso/src/components/common/Input/Input.jsx, gongjakso/src/pages/PostMainPage/PostMainPage.Styled.jsx, gongjakso/src/pages/PostMainPage/PostMainPage.jsx
1. 공고 페이지의 정렬, 기술 스택 드롭다운 UI 형식 수정
2. 스타일 적용
1. 각 공고 페이지의 정렬, 또는 기술 스택 드롭다운 클릭 시 디자인과 유사한지 확인부탁드려요
2. 드롭다운 외부 클릭 시 드롭다운이 닫히는지 확인부탁드려요
3. 정렬, 기술 스택 드롭다운의 옵션들이 잘 들어가있는지 확인부탁드려요
Issue Number:  #103
=> 🔀 Fix/editDropdownUI#103

gongjakso/src/components/common/Input/Input.Styled.jsx, gongjakso/src/components/common/Input/Input.jsx, gongjakso/src/components/common/Input/Multilevel.styled.jsx, gongjakso/src/pages/PostMainPage/PostMainPage.Styled.jsx, gongjakso/src/pages/PostMainPage/PostMainPage.jsx, gongjakso/src/pages/ProfilePage/ProfilePage.jsx, gongjakso/src/pages/ProfileParticipated/ParticipatedTeam.jsx, gongjakso/src/pages/TeamBox/TeamBox.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.jsx, gongjakso/src/service/auth_service.js, gongjakso/src/service/post_service.js
1. 게시글 불러오기 api 연동 완료
2. 개인 정보 수정 가능
1. 게시글이 잘 불러와지고, 클릭시 잘 넘어가지는 지 확인해주세요
2. 개인 정보 수정이 잘 되는지 확인 해주세요
Issue Number:  #86
=> 🔀Feat/postTeamBuildingApi#86 [게시글 API 연동 완]

gongjakso/src/pages/ProfileApplied/AppliedTeam.jsx, gongjakso/src/pages/ProfilePage/ProfilePage.jsx, gongjakso/src/pages/ProfileParticipated/ParticipatedTeam.jsx
1. 내가 지원한 팀 데이터 불러오기
2. 각 팀마다 최신 2개의 데이터만 불러오기
3. borderColor 적용 안된 부분 반영
1. 데이터 6개가 프로필 메인페이지에서 잘 보이는 지 봐주세요.
내가 지원한 팀의 경우 서버에서 넣어주신 데이터의 categoryList가 모두 비어있어서 값이 안나옵니다. (이상 없음!)
Issue Number:  #64
=> 🔀 Feat/profileApi#64

gongjakso/src/index.js, gongjakso/src/pages/CalendarPage/Calendar.jsx
1. calendar API 불러와 캘린더에 띄우기
2. 프로젝트 공모전 여부에 따라 스타일 적용
1. 캘린더에 스크랩한 post의 일정이 잘 표시되는지 확인 부탁드려요
2. 공모전은 파란색, 프로젝트는 핑크로 잘 나눠지는지 확인 부탁드려요
1. 2월, 3월 데이터로 확인 부탁드립니다
Issue Number:  #106
=> 🔀 Fix/editCalendarAPI#106

gongjakso/src/components/Auth/KakaoRedirectPage.jsx, gongjakso/src/features/modal/SignUpModal.jsx, gongjakso/src/pages/HomePage/HomePage.jsx, gongjakso/src/pages/PostMainPage/PostMainPage.jsx, gongjakso/src/pages/ProfileInfo/MyInfo.jsx, gongjakso/src/pages/ProfilePage/ProfilePage.jsx, gongjakso/src/service/auth_service.js, gongjakso/src/service/post_service.js, gongjakso/src/service/profile_service.js
1. 프로젝트/공모전 공고 검색창 api 연결
2. 팀빌딩 지역 드롭다운 스타일 수정
3. 로그아웃 후 로그인 => 마이페이지 들어가면 에러 해결
4. 정렬, 기술 스택 드롭다운 수정한 UI 바탕으로 api 연결
1. 전체적으로 잘 작동 하는지 확인해주세요
Issue Number:  #113
=> 🔀 Refactor/allConnetApi#113 [API, REFACTOR] api 연결 및 리팩토링

gongjakso/src/components/common/Input/Input.Styled.jsx, gongjakso/src/components/common/Input/Multilevel.styled.jsx, gongjakso/src/features/modal/ApplyModal.jsx, gongjakso/src/features/modal/ApplyModal.styled.jsx, gongjakso/src/features/modal/Completed.jsx, gongjakso/src/pages/DetailPage/DetailPageContest.jsx, gongjakso/src/pages/DetailPage/DetailPageProject.jsx, gongjakso/src/pages/DetailPage/DetailPageStyled.jsx, gongjakso/src/pages/PostMainPage/PostMainPage.Styled.jsx, gongjakso/src/pages/PostMainPage/PostMainPage.jsx, gongjakso/src/pages/TeamBox/TeamBoxStyled.jsx
1. 공모전 공고 페이지 전체적인 크기 수정
2. 프로젝트 공고 페이지 전체적인 크기 수정
3. 공고 클릭 시 공고 상세페이지의 맨 위로 이동 구현
4. 공고 상세페이지 전체적인 크기 수정
5. 지원하기 모달 지원 이유 스크롤 구현, 최대 높이 설정
6. 지원하기 모달 전체적인 크기 수정
7. 지원 완료 모달 전체적인 크기 수정
1. 프로젝트, 공모전 공고 페이지의 디자인이 유사한지 확인 부탁드려요
2. 공고 상세페이지의 디자인이 유사한지 확인 부탁드려요 (푸터 겹침 문제, x버튼 위치 조정, 크기 수정)
3. 공고 상세페이지로 이동 시 페이지의 맨 위로 이동되는지 확인 부탁드려요
4. 지원 이유의 최대 높이, 스크롤이 잘 구현되었는지 확인 부탁드려요
5. 지원하기 모달의 전체적인 디자인이 유사한지 확인 부탁드려요
6. 지원완료 모달의 전체적인 디자인이 유사한지 확인 부탁드려요
Issue Number:  #122
=> 🔀 Refactor/PostMainpage#122

gongjakso/src/pages/Portfolio/MyPortfolio.jsx, gongjakso/src/pages/Portfolio/MyPortfolioStyled.jsx, gongjakso/src/pages/ProfileApplied/AppliedTeam.jsx, gongjakso/src/pages/ProfilePage/ProfilePage.jsx, gongjakso/src/pages/ProfileParticipated/ParticipatedTeam.jsx, gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx, gongjakso/src/pages/TeamBox/TeamBox.jsx, gongjakso/src/router/Router.jsx
#120 프로필 업데이트
Issue Number:  #120
=> 🔀 Fix/mypage#120

gongjakso/src/features/modal/ApplyModal.jsx, gongjakso/src/pages/DetailPage/DetailPageContest.jsx, gongjakso/src/pages/DetailPage/DetailPageProject.jsx
1. 공고 상세페이지 버그 수정
1. 공고 상세페이지가 잘 보이는지 확인해주세요
Issue Number:  #121
=> 🔀 Refactor/PostdetailPage#121

gongjakso/src/components/Footer/Footer.jsx
1. 푸터 내 문자 2023 -> 2024 변경
2. 푸터 내 작성된 메일 수정
3. 문의하기 버튼 클릭 시 채널 링크로 이동 구현
1. 푸터 내 문자가 잘 수정되었는지 확인 부탁드려요
2. 문의하기 버튼 클릭 시 채널 링크로 잘 이동되는지 확인 부탁드려요
Issue Number:  #128
=> 🔀 Refactor/Footer#128

gongjakso/src/features/modal/ClickApply.jsx, gongjakso/src/features/modal/MyPageTeam.jsx, gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx
1. 내가 모집중인 팀 모달 및 페이지 id 연결 완료
1. 마이페이지에서 내가 모집중인 팀 클릭했을 때 링크가 teamdetail/id값 이 맞는지 확인해주세요
2. 모집 마감하기 또는 취소하기를 누르면 마이페이지에서 내가 모집중인 팀이 올바르게 사라지는 확인해주세요
Issue Number:  #131
=> 🔀 Refactor/RecruitPageID#131 

gongjakso/src/components/common/CountGuest/CountGuest.Styled.jsx, gongjakso/src/components/common/CountGuest/CountGuest.jsx, gongjakso/src/pages/HomePage/HomePage.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.jsx, gongjakso/src/service/auth_service.js
1. 팀빌딩 작업 페이지 스타일 기능 수정
1. 팀빌딩 작업 페이지 스타일 기능 이 잘 작동 하는지 확인해주세요
Issue Number:  #125
=> 🔀vRefactor/postUploadPage#125 [posting]

gongjakso/src/components/Header/Buttons.styled.jsx, gongjakso/src/components/Header/Header.Styled.jsx, gongjakso/src/components/common/Calendar/SelectCalendar.Styled.jsx, gongjakso/src/components/common/CountGuest/CountGuest.Styled.jsx, gongjakso/src/components/common/Input/Input.Styled.jsx, gongjakso/src/features/modal/ApplyModal.jsx, gongjakso/src/pages/CalendarPage/Calendar.styled.jsx, gongjakso/src/pages/HomePage/HomePage.Styled.jsx, gongjakso/src/pages/ProfilePage/ProfilePageStyled.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildPage.Styled.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildPage.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.Styled.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.jsx
1. 팀빌딩 페이지 스타일 보완
2. 팀빌딩 팀 만들기 페이지 스타일 보완
3. 헤더 스타일 보완
4. 마이페이지 첫 화면 스타일 보완
5. 캘린더 스타일 보완
6. 메인 페이지 스타일 보완
1. 팀빌딩 페이지 스타일이 잘 적용되었는지 확인 부탁드려요
2. 팀빌딩 팀 만들기 페이지 스타일이 잘 적용되었는지 확인 부탁드려요
3. 헤더 스타일이 잘 적용되었는지 확인 부탁드려요
4. 마이페이지 첫 화면 스타일이 잘 적용되었는지 확인 부탁드려요
5. 캘린더 스타일이 잘 적용되었는지 확인 부탁드려요
6. 메인 페이지 스타일이 잘 적용되었는지 확인 부탁드려요
Issue Number:  #133
=> 🔀 Refactor/AllpageStyle#133

gongjakso/src/components/common/Input/Multilevel.jsx, gongjakso/src/components/common/Input/Multilevel.styled.jsx
1. isPost 값에 맞게 드롭다운 스타일 및 폰트 수정 완료
1. isPost 값에 T,F 넣어서 스타일 잘 바뀌는지 확인해주세요
Issue Number:  #134
=> 🔀 Fix/DropStyle#134 [API]

gongjakso/package-lock.json, gongjakso/src/components/Auth/KakaoRedirectPage.jsx, gongjakso/src/components/Auth/Login.jsx, gongjakso/src/router/Router.jsx
1. 로그인이 안되던 문제 해결
1. 로그인이 잘 작동 하는지 확인해주세요
Issue Number:  #145
=> 🔀 Fix/LoginError#145 [로그인 에러 해결]

gongjakso/src/components/Pagination/Pagination.jsx, gongjakso/src/components/SwiperBanner/SwiperBanner.Styled.jsx, gongjakso/src/components/SwiperBanner/SwiperBanner.jsx, gongjakso/src/pages/PostMainPage/PostMainPage.jsx, gongjakso/src/pages/ProfileParticipated/ParticipatedTeam.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildPage.Styled.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildPage.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.jsx
1. 페이지 네이션 기능 추가
2. 배너 스타일 수정
3. 팀빌딩 상단 버튼 수정
1. 페이지 네이션이 잘 추가 되었는지 확인 해주세요
2. 배너 스타일이 알맞게 변경 되었는지 확인 해주세요
3. 팀빌딩 상단 버튼이 잘 수정 되었는지 확인해주세요 (클릭한 부분 하얀색 배경으로 변경)
Issue Number:  #146
=> 🔀 Refactor/editPagenationBanner#146 [페이지네이션 기능 추가 및 배너 수정]

gongjakso/src/pages/CalendarPage/Calendar.jsx
1. 캘린더에 스크랩한 공고 마감 일정 띄우기
1. 공고 스크랩 시 캘린더에 나타나는지 확인해주세요
2. 공고 스크랩 취소 시 캘린더에서 사라지는지 확인해주세요
3. 달에 해당하는 공고가 잘 나타나는지 확인해주세요
Issue Number:  #152
=> 🔀 Fix/CalendarAPI#152

gongjakso/src/features/modal/ApplyModal.jsx, gongjakso/src/features/modal/ApplyModal.styled.jsx, gongjakso/src/features/modal/Completed.jsx, gongjakso/src/pages/DetailPage/DetailPageContest.jsx, gongjakso/src/pages/DetailPage/DetailPageProject.jsx, gongjakso/src/pages/DetailPage/DetailPageStyled.jsx, gongjakso/src/pages/PostMainPage/PostMainPage.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.jsx
1. 공고 상세페이지 전체적인 크기 조절
2. 지원하기 한번 더 확인 모달창 추가 및 API 연결 완료
3. 지원자 입장에서의 공고 상세페이지 조건 추가 및 UI 완성
4. 아직 지원자 공고 상세페이지에서의 지원서 보기는 연결X
1 .공고 상세페이지에서 지원하기를 할 때 한번 더 확인 모달창이 잘 나오는지 확인해주세요
2. 지원하기를 눌렀을 때 콘솔창에 정상적인 요청이 뜨는지 확인해주세요
Issue Number:  #155
=> 🔀 Fix/TotalDetailPageModalUI#155 [스타일 수정 및 모달 추가]

gongjakso/src/pages/HomePage/HomePage.jsx, gongjakso/src/pages/HomePage/ScrollHandler.jsx, gongjakso/src/pages/HomePage/TopButton.Styled.jsx, gongjakso/src/pages/HomePage/TopButton.jsx
1. 메인페이지 애니메이션 추가
2. 탑버튼 기능과 겹치는 부분 해결
1. 화면 스크롤 시 컨텐츠 한 영역별로 이동이 잘 되는지 확인 부탁드려요
2. 탑버튼을 눌렀을 경우 맨 위로 잘 올라가는지 확인 부탁드려요
3. 부자연스러운 부분이 없는지 확인 부탁드려요
Issue Number:  #158
=> 🔀 Feat/mainPageAnimation#158

gongjakso/src/features/modal/ApplyModal.jsx, gongjakso/src/features/modal/ApplyModal.styled.jsx, gongjakso/src/features/modal/ClickApply.jsx, gongjakso/src/features/modal/ClickmyApply.jsx, gongjakso/src/pages/DetailPage/DetailPageContest.jsx, gongjakso/src/pages/DetailPage/DetailPageProject.jsx, gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx, gongjakso/src/pages/ProfileRecruit/ProfileRecruit.styled.jsx, gongjakso/src/service/apply_service.js, gongjakso/src/service/post_service.js
1. 공고 상세페이지 수정된 API 연결 및 수정 완료 -> 아직 **회의지역은 서버 수정중**이랍니다!! (회의지역X)
2. 스크랩하기 새로고침 제거
3. 팀장일때 / 지원자일때 / 일반인일때 공고 상세페이지 각기 다르게 구현 완료
4. 지원자 입장일 때, 지원서보기 클릭 시 자신의 지원서 볼 수 있게끔 구현 완료
5. 내가 모집중인 팀 수정된 API 연결 및 수정 완료
6. 내가 모집중인 팀에서 팀장이 자기 공고 볼 수 있게끔 하는 버튼 구현 완료
7. 지원서보기 클릭 시, 미선발 혹은 합류했을 경우 아래 버튼 없애고 모달 안에 상태 표시 버튼 추가 완료
8. 지원자가 지원 취소 시, 행 색깔 변하는 것 디자인 추가 완료
1. 공고 상세페이지가 잘 뜨는지 확인해주세요! (현재 회의지역은 안뜨는게 맞습니다!)
2. 스크랩하기 눌렀을 때 색깔이 잘 바뀌는지 확인해주세요!
3. 사용자 상태 별로 공고 상세페이지가 다르게 잘 보이는지 확인해주세요
- 팀장 : 아래 버튼이 아예 다 사라집니다
- 지원자 : 타이틀 옆에 사용자 선발 상태가 뜨고 지원서보기 버튼이 있습니다. 지원서 보기 눌렀을 때 지원서가 잘 뜨는지 확인해주세요
- 일반인  : 기존 디자인과 동일합니다
4. 내가 모집중인 팀 페이지가 오류 없이 잘 뜨는지 확인해주세요
5. 지원자 상태를 결정했을 때 (새로고침 해야합니다!) 현재 상태가 잘 바뀌었는지, 지원서 보기 눌렀을 때 모달 디자인이 잘 바뀌었는지 확인해주세요
Issue Number:  #165
=> 🔀 Refactor/fixAPI#165 [API 전체 수정 및 UI 추가]

gongjakso/src/components/Pagination/Pagination.jsx, gongjakso/src/components/common/Input/Multilevel.jsx, gongjakso/src/features/modal/Modal.Styled.jsx, gongjakso/src/features/modal/SignUpModal.jsx, gongjakso/src/pages/CalendarPage/Calendar.jsx, gongjakso/src/pages/CalendarPage/Calendar.styled.jsx, gongjakso/src/pages/PostMainPage/PostMainPage.jsx, gongjakso/src/pages/ProfileInfo/MyInfo.jsx, gongjakso/src/pages/ProfileInfo/MyInfoStyled.jsx, gongjakso/src/pages/ProfilePage/ProfilePage.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.jsx, gongjakso/src/service/calendar_service.js, gongjakso/src/service/post_service.js, gongjakso/src/service/profile_service.js
1. 지역 데이터 시/구 나누기
2. 개인정보에 연락처 란 추가
3. 캘린더 이벤트 클릭시 해당 공고 이동 기능 추가
4. 전체적인 오류 수정
1. 해당 PR에 각자의 수정된 내용이 잘 반영 됐는지 확인해주세요
2. 공모전에서 지역 검색 시 "서울 구로구"에 검색이 잘 되는지 확인해주세요
3. 캘린더 이벤트 클릭 시 해당하는 공고 상세페이지로 이동하는지 확인해주세요
4. 전체적으로 오류는 없는지 스타일에 오류는 없는지 확인해주세요
Issue Number:  #161
=> 🔀 Refactor/editSearchLocal#161 [지역 데이터 나누기, 연락처 추가, 캘린더 기능 추가, 전체적인 오류 수정]

gongjakso/src/features/modal/ClickApply.jsx, gongjakso/src/pages/DetailPage/DetailPageContest.jsx, gongjakso/src/pages/DetailPage/DetailPageProject.jsx, gongjakso/src/pages/DetailPage/DetailPageStyled.jsx
1. 상세페이지 전체 디자인 보완 및 수정
1. 지원자 입장 공고 상세페이지에서 지원서 보기 버튼 옆 현재 모집 상태 버튼이 올바르게 잘 표시되는지 확인해주세요
2. 오픈카톡 문의 링크를 눌렀을 때 local3000 링크가 아닌 외부 링크로 잘 이동되는지 확인해주세요
3. 오픈카톡, 구글폼 구분 추가 (T/F값에 따라..)
Issue Number:  #169
=> 🔀 Refactor/fixPost#169 [스타일 수정]

gongjakso/src/pages/ProfileApplied/AppliedTeam.jsx, gongjakso/src/pages/ProfilePage/ProfilePage.jsx, gongjakso/src/pages/ProfileParticipated/ParticipatedTeam.jsx, gongjakso/src/pages/TeamBox/TeamBox.jsx, gongjakso/src/pages/TeamBox/TeamBoxStyled.jsx
1. 모든 팀박스 공모전/프로젝트 테두리 색 정확히 바뀌도록 반영
(활동종료 -> 테두리 검은색의 경우 백엔드 측에서 api 수정 중에 있다고 하여 추후 추가 수정 작업할 예정입니다.)
1. 내가 지원한 팀과 내가 참가한 팀의 상세페이지가 제대로 뜨는지 확인해주세요.
2. 팀박스 테두리가 공모전/프로젝트에 맞게 하늘/핑크색으로 반영이 되었는지 확인해주세요.
Issue Number:  #164
=> 🔀 Refactor/AppliedTeamBoxApi#164

gongjakso/src/components/Header/Buttons.jsx
#173 헤더 커서 오류 해결
1. 로그인 전 헤더 부분 버튼 클릭 시 뜨는 모달에서 X를 눌렀는데 헤더에 커서가 풀리지 않는 오류 해결
1. 헤더에 커서가 제대로 잘 작동하는지 확인해주세요
Issue Number:  #173
=> 🔀 Fix/HeaderPointerError#173

gongjakso/src/assets/mapData/mapData.jsx, gongjakso/src/components/SwiperBanner/SwiperBanner.jsx, gongjakso/src/components/common/Input/Input.jsx, gongjakso/src/components/common/Input/Multilevel.jsx, gongjakso/src/pages/PostMainPage/PostMainPage.jsx, gongjakso/src/service/post_service.js
1. 공고 페이지 배너 클릭시 해당 링크 이동 작업
2. 검색 부분 스페이스 포함되게 검색되도록 수정
3. 조건 옵션 선택에 기본값 추가
Issue Number:  #175
=> 🔀 Refactor/PostPage#175 [공고페이지 리팩토링]

gongjakso/src/features/modal/ApplyCancel.jsx, gongjakso/src/features/modal/ApplyModal.jsx, gongjakso/src/features/modal/ApplyModal.styled.jsx, gongjakso/src/features/modal/ClickApply.jsx, gongjakso/src/features/modal/ClickmyApply.jsx, gongjakso/src/features/modal/Completed.jsx, gongjakso/src/features/modal/MyPageTeam.jsx, gongjakso/src/pages/DetailPage/DetailPageContest.jsx, gongjakso/src/pages/DetailPage/DetailPageProject.jsx, gongjakso/src/pages/DetailPage/DetailPageStyled.jsx, gongjakso/src/service/apply_service.js
#171 전체적인 스타일 및 모달 크기 조정과 지원 취소 모달 추가
1. 공고 상세페이지 / 내가 모집중인 팀 / 전체적인 모달 스타일 깨짐 수정 완료
2. 전체적으로 수정된 api 반영 완료
3. 지원 취소 버튼 모달 추가 및 지원 취소 api 연결 완료
4. 공고 상세페이지 설명글 500자에 맞게 스타일 조정 및 지원 이유 1000자로 늘리기 반영 완료
1. 공고 상세페이지랑 전체적인 모달 스타일이 깨지는 부분이 있는지 확인해주세요
2. 공고 상세페이지와 내가 모집중인 팀 페이지 내 글자가 빠진 부분이 있는지 확인해주세요 (api 오류 없는지,,)
3. 지원 취소 클릭 시 모달이 올바르게 뜨는지 확인해주세요
4. 지원하기 눌렀을 때 지원 이유가 총 1000자로 올바르게 늘어났는지 확인해주세요 
Issue Number:  #171
=> 🔀 Fix/TotalStyleAPI1#171 [스타일 크기 조정]

gongjakso/src/components/Auth/KakaoRedirectPage.Styled.jsx, gongjakso/src/components/Auth/KakaoRedirectPage.jsx, gongjakso/src/components/Header/Bubble.Styled.jsx, gongjakso/src/components/Header/Bubble.jsx, gongjakso/src/components/common/Input/infoDrop.styled.jsx, gongjakso/src/features/modal/Modal.Styled.jsx, gongjakso/src/features/modal/SignUpModal.jsx
1. 로그인 후 보고 있던 페이지로 돌아오도록 수정
2. 회원가입 모달의 모든 입력값을 받아야 완료 버튼 색 변경과 클릭이 가능하도록 구현
3. 로그인 모달에 있는 버튼 사이즈 조정
4. 마이페이지 모달에 나타나는 이름과 전공 배치 수정
5. 회원가입 모달 사이즈 수정
1. 보고 있던 페이지에서 모달을 이용해 로그인 후 다시 보고 있던 페이지로 돌아오는지 확인 부탁드려요 
2. 회원가입 모달의 모든 값을 입력받아야 회색->파란 버튼이 되는지, 클릭이 되는지 확인 부탁드려요
3. 로그읜 모달의 버튼 사이즈가 적절한지 확인 부탁드려요 (ex: 로그인하기/ 로그인하지 않고 둘러보기)
4. 마이페이지 모달에 나타나는 이름과 전공 영역이 적절히 배치되었는지 확인 부탁드려요
5. 회원가입 모달의 글씨 크기와 영역의 크기들이 적절히 조정되었는지 확인 부탁드려요
Issue Number: #177
=> 🔀 Refactor/LoginModal#177

gongjakso/src/pages/Portfolio/MyPortfolio.jsx, gongjakso/src/pages/Portfolio/MyPortfolioStyled.jsx, gongjakso/src/pages/ProfileParticipated/ParticipatedTeam.jsx
1. 이메일 유효성 검사 추가 -> 이메일 형식 아닐 경우 경고 모달 뜸
2. 이메일 작성 칸의 placeholder 가 잘리지 않도록 수정
3. 로그인 된 경우 본인의 이메일 바인딩 되도록 함
4. 이메일을 정상적으로 입력한 경우 / 이메일 유효성 검사에 어긋나는 경우 / 이미 전송한 이메일의 경우 -> 3가지 상황에 따라 적절한 모달이 뜸
1. 이메일 유효성 검사 추가하였습니다. 이메일 형식 아닐 경우 경고 모달 뜨는지 봐주세요.
2. 이메일 작성 칸의 placeholder 가 잘리지 않는지 확인해 주세요.
3. 로그인 된 경우 본인의 이메일 바인딩 되는지 봐주세요.
4. 이메일을 정상적으로 입력한 경우 / 이메일 유효성 검사에 어긋나는 경우 / 이미 전송한 이메일의 경우 -> 이렇게 3가지 상황에 따라 적절한 모달이 뜨는지 확인해 주세요.
Issue Number:  #182
=> 🔀Refactor/portfolioUI#182

gongjakso/src/components/Auth/KakaoRedirectPage.jsx, gongjakso/src/pages/ScrapPage/Scrap.jsx
1. 로그인 후 홈으로 이동
2. 스크랩 공고가 없을 경우 스크랩 존재 x 문구 표시
1. 로그인 후 홈으로 이동하도록 변경
2. 스크랩 공고가 없을 경우 스크랩 존재 x 문구 표시
Issue Number:  #193
=> 🔀 Fix/LoginError#193

gongjakso/src/pages/Portfolio/MyPortfolio.jsx, gongjakso/src/pages/Portfolio/MyPortfolioStyled.jsx, gongjakso/src/pages/ProfileApplied/AppliedTeam.jsx, gongjakso/src/pages/ProfilePage/ProfilePage.jsx, gongjakso/src/pages/ProfileParticipated/ParticipatedTeam.jsx, gongjakso/src/pages/TeamBox/TeamBox.jsx, gongjakso/src/pages/TeamBox/TeamBoxStyled.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.jsx, gongjakso/src/service/profile_service.js
1. 내가 지원한 팀 오버레이 UI 구현
1. 내가 지원한 팀 오버레이 UI 가 피그마와 일치한 지 봐주세요.
1. TeamBox.jsx 파일 142 번째 줄에서 작업 파일 내 status가 모두 RECRUITING으로 되어있어 작업을 위해 잠깐 변경해두었습니다.
추후 EXTENSION으로 수정 부탁드립니다.
`{postContent?.status === 'RECRUITING' && ( //RECRUITING -> EXTENSION으로 변경해야함
`
2. 닫기 버튼 클릭시 닫기 버튼만 사라집니다.
Issue Number:  #183
=> 🔀Refactor/mypageAppliedApi#183

gongjakso/src/pages/DetailPage/DetailPageContest.jsx, gongjakso/src/pages/DetailPage/DetailPageProject.jsx
#194 스크랩 오류 수정 완료
1. 스크랩 오류 해결 완료
1. 스크랩하기 버튼이 오류 없이 잘 작동되는지 확인해주세요 (아직 실시간 반영은 안됩니다!)
Issue Number:  #194
=> 🔀 Fix/NewScrap#194 [변경된 API 변수 반영 완료]

gongjakso/src/App.js, gongjakso/src/pages/ProfilePage/ProfilePage.jsx, gongjakso/src/pages/ProfileParticipated/ParticipatedTeam.jsx, gongjakso/src/pages/ProfileRecruit/ProfileRecruit.styled.jsx, gongjakso/src/pages/TeamBox/TeamBox.jsx
#197 refactor styled
1. 전체적인 스타일 수정 및 오류점검
Issue Number:  #197
=> 🔀 Refactor/InspectionandFeat#197

gongjakso/src/components/Header/Buttons.jsx, gongjakso/src/pages/ContestDetailPage/ContestDetailPage.Styled.jsx, gongjakso/src/pages/ContestDetailPage/ContestDetailPage.jsx, gongjakso/src/pages/ContestListBox/ContestListBox.Styled.jsx, gongjakso/src/pages/ContestListBox/ContestListBox.jsx, gongjakso/src/pages/ContestListPage/ContestListPage.jsx, gongjakso/src/router/Router.jsx
1. 공모전 리스트에서 단일 공모전 클릭시 페이지 이동하도록 구현
1. 공모전 리스트에서 단일 공모 클릭
2. 단일 공모전 클릭시 헤더 색이 유지되는지 확인해주세요
3. 단일 공모전 클릭 후 페이지가 잘 이동 되는지 확인해주세요
4. 안에 넣은 데이터는 임시 데이터 입니다.
5. 단일 공모전 페이지가 사이즈가 적당한지 확인해주세요
6. 단일 공모전에서 팀빌딩하러 가기 클릭시 팀빌딩 페이지로 이동하는지 확인해주세요
Issue Number:  #214
=> 🔀 Refactor/singleContestPageUI#214 [단일 공모전 페이지 구현]

gongjakso/src/components/common/Calendar/SelectDate.Styled.jsx, gongjakso/src/components/common/Calendar/SelectDate.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildPage.Styled.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildPage.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.Styled.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.jsx
1. 팀빌딩 페이지 디자인을 참고하여 수정
1. 양식들이 디자인과 똑같이 구성 되어 있는지 확인해주세요
Issue Number:  #220
=> 🔀 Refactor/editTeamBuildingPage#220 [팀빌딩 페이지 UI 수정]

gongjakso/src/pages/ContestDetailPage/ContestDetailPage.Styled.jsx, gongjakso/src/pages/ContestDetailPage/ContestDetailPage.jsx, gongjakso/src/pages/ContestListBox/ContestListBox.Styled.jsx, gongjakso/src/pages/ContestListBox/ContestListBox.jsx, gongjakso/src/pages/ContestListPage/ContestListPage.jsx, gongjakso/src/service/auth_service.js, gongjakso/src/service/axiosInstance.js, gongjakso/src/service/post_service.js
#222 ContestList API 연결 완료
1. 공모전 리스트 api 를 연결해서 공모전 리스트를 불러옴
1. 공모전 리스트 페이지에 해당하는 공모전데이터들이 잘 보이는지 확인해주세요
2. 공모전 단일 클릭 시 공모전 내용이 다음 페이지로 잘 전달 되는지 확인해주세요
@sxxcxng 
Issue Number:  #222
=> 🔀 Feat/contestListApi#222 [공모전 리스트 API 연결]

gongjakso/src/index.js, gongjakso/src/pages/ContestDetailPage/ContestDetailPage.Styled.jsx, gongjakso/src/pages/ContestDetailPage/ContestDetailPage.jsx, gongjakso/src/pages/TeamBox/TeamBox.jsx, gongjakso/src/service/apply_service.js, gongjakso/src/service/auth_service.js, gongjakso/src/service/axiosInstance.js, gongjakso/src/service/calendar_service.js, gongjakso/src/service/post_service.js, gongjakso/src/service/profile_service.js
#226 contestTeamListApi 연결
1. 공모전 별로 불러오는 팀 리스트 api 연결
1. 공모전별로 리스트를 불러오는게 보이는지 확인해주세요
Issue Number:  #226
=> 🔀 Feat/contestTeamListApi#226 [contestTeamList Api 연결]

gongjakso/src/pages/HomePage/HomePage.jsx
#231 로그인 여부에 따른 버튼 기능 추가
1. 메인페이지 로그인 여부에 따른 버튼 디자인 및 이동 로직 추가하였습니다.
1. 로그인 여부에 따라 해당 버튼 기능과 디자인이 잘 변경되는지 확인 부탁드려요
Issue Number:  #231
=> 🔀 Feat/mainPageBtn#231 [메인페이지 버튼 기능추가]

gongjakso/src/components/common/CountGuest/CountGuest.jsx, gongjakso/src/hooks/useNavigate.js, gongjakso/src/pages/ContestDetailPage/ContestDetailPage.jsx, gongjakso/src/pages/TeamBox/TeamBox.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildPage.Styled.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildPage.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.Styled.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.jsx, gongjakso/src/service/post_service.js
1. 팀빌딩 페이지 api 연결 완료
1. 모든 양식을 입력하고, 해당하는 공모전에 맞는 팀빌딩이 잘 이루어지는지 확인해주세요
2. 양식을 하나씩 비워 보면서 팀빌딩 하는 과정에서 오류가 없는지 확인해주세요
Issue Number:  #227
=> 🔀 Feat/teamBuildingApi#227 [팀 빌딩 페이지 API 연결]

gongjakso/src/features/modal/ApplyModal.styled.jsx, gongjakso/src/features/modal/Completed.jsx, gongjakso/src/pages/ContestDetailPage/ContestDetailPage.jsx, gongjakso/src/pages/DetailPage/DetailPageContest.jsx, gongjakso/src/router/Router.jsx, gongjakso/src/service/apply_service.js, gongjakso/src/service/post_service.js
1. 공고 상세페이지 api 연결 완료
2. 지원하기 api 연결 완료
3. 아직 지원자 상태 (leader/general/applier) 별 공고 상세페이지는 서버 문제로 미완인 상태
1. 공고 상세페이지에 데이터가 잘 들어가 있는지 확인해주세요
2. 지원하기가 잘 작동하는지 확인해주세요
Issue Number:  #228
=> 🔀 Feat/PostDetailAPI#228 [공고 상세페이지 및 지원하기 API]

gongjakso/src/features/modal/ApplyCancel.jsx, gongjakso/src/pages/DetailPage/DetailPageContest.jsx, gongjakso/src/pages/DetailPage/DetailPageStyled.jsx, gongjakso/src/service/apply_service.js, gongjakso/src/service/post_service.js
사용자 상태 별 공고 상세페이지 api 연결 완료
1. 지원한 공고 상세페이지에서의 정보가 잘 뜨는지 확인해주세요
Issue Number:  #236
=> 🔀 Feat/UserDetailPageAPI#236 [사용자 상태 별 공고상세페이지 API]

gongjakso/src/pages/ContestDetailPage/ContestDetailPage.Styled.jsx, gongjakso/src/pages/ContestListBox/ContestListBox.Styled.jsx, gongjakso/src/pages/ContestListBox/ContestListBox.jsx, gongjakso/src/pages/Portfolio/MakePortfolio.jsx, gongjakso/src/pages/Portfolio/Portfolio.Styled.jsx, gongjakso/src/pages/Portfolio/UsePortfolio.jsx, gongjakso/src/pages/PostMainPage/PostMainPage.Styled.jsx, gongjakso/src/pages/ProfilePage/ProfilePage.jsx, gongjakso/src/pages/ProfilePage/ProfilePageStyled.jsx, gongjakso/src/pages/TeamBox/TeamBox.jsx, gongjakso/src/router/Router.jsx, gongjakso/src/service/portfolio_service.js
1. 존재하는 포트폴리오 api 연결 (조회, 삭제, 수정)
2. 디자인 수정
1. 포트폴리오 등록이 잘 이루어지는지 확인 부탁드려요
현재 노션과 pdf가 한 포트폴리오 아이디로 받아와서 하나의 컴포넌트에 있습니다
이 부분 수정할 예정입니다
Issue Number: #233
=> 🔀 Feat/ExistPortfolio#233

gongjakso/src/features/modal/ApplyCancel.jsx, gongjakso/src/features/modal/ApplyModal.styled.jsx, gongjakso/src/features/modal/Completed.jsx, gongjakso/src/pages/DetailPage/DetailPageContest.jsx, gongjakso/src/pages/DetailPage/DetailPageStyled.jsx, gongjakso/src/service/post_service.js
공고 상세페이지 최종 api 연결 및 스타일 조정 완료
1. 공고 상세페이지 전체적인 부분이 최종적으로 잘 작동하는지 확인해주세요
Issue Number:  #241
=> 🔀 Refactor/PostDetailPagefinal#241 [공고 상세페이지 최종]

gongjakso/src/pages/Portfolio/MakePortfolio.jsx, gongjakso/src/pages/Portfolio/Portfolio.Styled.jsx, gongjakso/src/pages/Portfolio/UsePortfolio.jsx, gongjakso/src/pages/ProfilePage/ProfilePage.jsx, gongjakso/src/pages/ProfilePage/ProfilePageStyled.jsx, gongjakso/src/service/portfolio_service.js
1. 포트폴리오 만든 적이 있는 사용자가 포트폴리오를 다 지우고 새로고침했을 경우 발생하는 컴포넌트 오류 수정하였습니다.
2. 동일한 아이디의 포트폴리오에 notion, pdf 링크가 모두 존재할 경우 프로필에서 분리하였습니다,
3. 프로필 포트폴리오 추가 부분: 3.의 컴포넌트를 분리한 후 각각을 1개의 컴포넌트로 계산해 3개가 되면 플러스버튼 사라지도록 구현하였습니다.
4. 이미 notion과 pdf링크를 한개씩 등록하였을 경우, 추가로 링크를 등록하려고 할때 페이지에 에러 메시지 추가하였습니다.
1. 포트폴리오 만든 적이 있는 사용자가 포트폴리오를 다 지우고 새로고침했을 경우 발생하는 컴포넌트 오류 해결되었는지 확인부탁드려요
2. 동일한 아이디의 포트폴리오에 notion, pdf 링크가 모두 존재할 경우 프로필에서 분리가 잘 되었는지 확인부탁드려요
3. 프로필 포트폴리오 추가 부분: 3.의 컴포넌트를 분리한 후 각각을 1개의 컴포넌트로 계산해 3개가 되면 플러스버튼아 사라지는지 확인부탁드려요
4. 이미 notion과 pdf링크를 한개씩 등록하였을 경우, 추가로 링크를 등록하려고 할때 페이지에 에러 메시지 추가되었는지 확인부탁드려요
Issue Number: #239
=> 🔀 Fix/Portfolio#239 [포트폴리오 오류 수정]

gongjakso/src/features/NoContents/NoContents.styled.jsx, gongjakso/src/pages/ContestDetailPage/ContestDetailPage.Styled.jsx, gongjakso/src/pages/ContestDetailPage/ContestDetailPage.jsx, gongjakso/src/pages/ContestListPage/ContestListPage.jsx, gongjakso/src/pages/HomePage/HomePage.jsx, gongjakso/src/pages/Portfolio/Portfolio.Styled.jsx, gongjakso/src/pages/Portfolio/UsePortfolio.jsx, gongjakso/src/pages/PostMainPage/PostMainPage.jsx, gongjakso/src/pages/ProfileApplied/AppliedTeam.jsx, gongjakso/src/pages/ProfilePage/ProfilePage.jsx, gongjakso/src/pages/ProfileParticipated/ParticipatedTeam.jsx, gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx, gongjakso/src/pages/ProfileRecruited/RecruitedTeam.jsx, gongjakso/src/pages/ScrapPage/Scrap.jsx, gongjakso/src/pages/TeamBox/TeamBox.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildPage.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.jsx, gongjakso/src/service/apply_service.js, gongjakso/src/service/auth_service.js, gongjakso/src/service/post_service.js, gongjakso/src/service/profile_service.js
1. 공모전 리스트에서 정렬과 키워드 검색이 가능함
2. 공모전 공고 페이지에서 모든 공모전을 한눈에 볼 수 있음
3. 개별 공모전에 들어가서 해당하는 팀들을 정렬할 수 있음 -> 인기순 정렬 변수가 필요
4. UI 수정 피드백 적용
5. 원하는 공모전 없을 시 페이지 이동하는 버튼 구현
6. 첫 로그인 시 뜨지 않던 모달 수정
Issue Number:  #240
=> 🔀Refactor/editQAProblem#240 [QA 피드백 적용]

gongjakso/src/features/modal/MyPageTeam.jsx, gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx, gongjakso/src/service/apply_service.js
모집취소 API 추가#246
1. 모집 취소 API 코드 수정
=> 🔀 모집 취소 API 추가

gongjakso/src/pages/ProfilePage/ProfilePage.jsx, gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx, gongjakso/src/pages/TeamBox/TeamBox.jsx, gongjakso/src/service/apply_service.js, gongjakso/src/service/profile_service.js
=> 🔀 Refactor/finalTestandFeat#249 [마지막 점검 및 구현]

gongjakso/src/pages/HomePage/HomePage.Styled.jsx
1. 메인페이지 컴포넌트 사이즈 수정하였습니다
1. 메인페이지 컴포넌트 사이즈가 적절한지 확인부탁드러요
Issue Number: #252
=> 🔀 Refactor/ComponentSize#252 [메인페이지 컴포넌트 사이즈 수정]

gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx, gongjakso/src/service/apply_service.js
1. 내가 모집중인 팀의 상세페이지에서 지원자의 미선발/합류하기 버튼 API 구현
지원자 선택 후 미선발/합류하기 버튼 클릭시 알맞게 버튼이 수정되는지 확인해주세요.
=> 🔀 Refator/recruitButtomAPI#254 [API 구현]

gongjakso/src/App.js, gongjakso/src/components/common/AlertModal/AlertModal.Styled.jsx, gongjakso/src/pages/ContestDetailPage/ContestDetailPage.jsx, gongjakso/src/pages/ContestListPage/ContestListPage.jsx, gongjakso/src/pages/PostMainPage/PostMainPage.jsx, gongjakso/src/service/post_service.js
#258 모달 수정 및 모바일 사이즈 수정
1. 팀 빌딩 시 모달 사이즈 수정
2. 모바일 사이즈 수정
Issue Number:  #258
=> 🔀 Refactor/editFinalUI#258 [팀빌딩 시 모달 수정 및  모바일 사이즈 수정]

gongjakso/src/features/modal/DeleteModal.jsx, gongjakso/src/pages/HomePage/HomePage.Styled.jsx, gongjakso/src/pages/Portfolio/UsePortfolio.jsx, gongjakso/src/pages/ProfilePage/ProfilePage.jsx, gongjakso/src/service/portfolio_service.js
1. 포트폴리오 상세 조회 api 로직 수정하였습니다.
2. 포트폴리오 삭제 api 로직 수정하였습니다.
3. 포트폴리오 편집 api 로직 수정하였습니다.
1. 등록된 포트폴리오가 링크별로 프로필 내 컴포넌트에 잘 불러와지는지 확인부탁드려요
2. 포트폴리오 편집 페이지가 잘 들어가지고, 기능이 잘 작동하는지 확인부탁드려요
3. 포트폴리오 삭제 요청이 잘 가는지 확인부탁드려요
=> 🔀 Refactor/PortfolioApi#259 [포트폴리오 로직 수정]

gongjakso/src/features/modal/ApplyModal.styled.jsx, gongjakso/src/features/modal/ClickmyApply.jsx, gongjakso/src/features/modal/Completed.jsx, gongjakso/src/pages/DetailPage/DetailPageContest.jsx, gongjakso/src/service/apply_service.js, gongjakso/src/service/post_service.js
공고 상세페이지 '지원서 보기' 버튼 클릭 시 띄워지는 임시 모달 추가 완료
-> 추후 pdf 파일 다운되는것으로 변경 예정
공고 상세페이지 부분 '지원서 보기' 버튼 클릭 시, 모달이 알맞게 뜨는지 확인해주세요 
Issue Number:  #262
=> 🔀 Feat/PostpageMyApply#262 [나의 지원서보기 임시 모달 추가]

gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx, gongjakso/src/service/apply_service.js
#265 모집중인팀 합류완료/미선발 버튼 API 상태값 수정
1. 내가 모집 중인 팀 상세페이지 지원자 합류완료/미선발 API 오류 수정
1. 지원자 선택 후 합류완료 또는 미선발 버튼 클릭시 그에 맞는 버튼이 생성되는지 확인해주세요.
=> 🔀Feat/recruitStateAPI#265

gongjakso/src/components/Header/Bubble.jsx, gongjakso/src/pages/ProfileApplied/AppliedTeam.jsx, gongjakso/src/pages/ProfilePage/ProfilePage.jsx, gongjakso/src/pages/ProfileParticipated/ParticipatedTeam.jsx, gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx, gongjakso/src/pages/ProfileRecruited/RecruitedTeam.jsx, gongjakso/src/pages/ScrapPage/Scrap.jsx, gongjakso/src/pages/TeamBox/TeamBox.jsx, gongjakso/src/pages/TeamBox/TeamBoxStyled.jsx, gongjakso/src/service/apply_service.js, gongjakso/src/service/profile_service.js
1. 사용자가 지원한 팀에 대한 공고 올바르게 노출되도록 구현
2. 상세페이지에서 팀박스 클릭시 공고 노출되도록 구현
3. 팀장이 [합류하기] 버튼 눌렀을 때 상태가 [합류완료]로 바뀌도록 구현
4. 프로필 아이콘 클릭시 '000님의 00 기록'으로 통일
5. 팀박스에서 내가 지원한 파트명만 나오도록 수정 (현재는 공고의 모집 파트가 모두 뜸)
1. 프로필 아이콘 클릭시 '000님의 00 기록'으로 통일되었는지 확인해주세요.
2. (모집/지원/참여/스크랩) 상세 페이지 제목이 '000님의 00 기록/000님의 스크랩'으로 수정이 잘 되어있는지 확인해주세요.
3. 지원 기록 페이지에 현재까지 지원한 팀박스가 잘 뜨는지 확인해주세요.
4. 지원 기록 페이지에서 팀박스 클릭시 공고가 뜨는지 확인해주세요.
5. 지원 팀박스가 현재 상태에 맞게 '미선발/합류완료/합류대기중'으로 알맞게 뜨는지 확인해주세요.
Issue Number:  #264
=> 🔀Feat/applyAPI#264

gongjakso/src/pages/Portfolio/MakePortfolio.jsx, gongjakso/src/pages/Portfolio/UsePortfolio.jsx, gongjakso/src/pages/ProfilePage/ProfilePage.jsx
1. 포트폴리오 파일 삭제 시 노션 편집 페이지에서 노션uri 안보이는 오류 헤결
2. 입력하는 포트폴리오에서 학년, 상태, 활동 상태 placeholder 지정 후, 선택하지 않았을 경우 빈 값 전송
3. 프로필 페이지에서 팀박스 타이틀명 수정
1. 포트폴리오 파일 삭제 시 노션 편집 페이지에서 노션uri 안보이는 오류 헤결되었는지 확인 부탁드려요 
(파일, 노션 같이 작성한 후 파일만 삭제 -> 노션 수정하러 들어가기)
2. 입력하는 포트폴리오에서 학년, 상태, 활동 상태 placeholder로 보이는지, 지정하지 않았을 경우 아무런 값이 넘어가지 않는지 확인 부탁드려요
3. 프로필 페이지에서 팀박스 타이틀명 수정되었는지 확인 부탁드려요
Issue Number:  #270
=> 🔀 Fix/PortfolioApi#270 [포트폴리오 오류 수정]

gongjakso/src/components/common/Calendar/SelectDate.jsx, gongjakso/src/features/modal/ClickRecruitApplicant.jsx, gongjakso/src/features/modal/MyPageTeam.jsx, gongjakso/src/pages/ProfileApplied/AppliedTeam.jsx, gongjakso/src/pages/ProfileParticipated/ParticipatedTeam.jsx, gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx, gongjakso/src/pages/ProfileRecruited/RecruitedTeam.jsx, gongjakso/src/pages/TeamBox/TeamBox.jsx, gongjakso/src/service/apply_service.js
1. 내가 모집 중인 팀 - 팀장이 모집 취소시 '나의 모집 기록' 내의 팀박스에서 모집 마감시 - [마감] / 모집 취소시 - [취소]로 뜨도록 구현
2. 내가 모집 중인 팀 - 상세페이지에서 '연장하기' -> 마감 일자 기준 연장이 아닌 앞당김도 가능한 점 해결 (모집마감일자 기준 그 이후로만 가능하도록)
3. 내가 모집 중인 팀 - 상세페이지에서 지원자의 '지원서 보기' 클릭시 지원서 모달 뜨도록 구현
4. 내가 모집 중인 팀 - 상세페이지에서 포트폴리오가 없는 경우 '지원서 보기'만 뜨도록 구현
5. 내가 모집 중인 팀 - 상세페이지에서 '현재 모집 현황'의 지원현황 수를 '합류 완료'된 수로 변경
위 작업 내역이 올바르게 작동되는지 확인해주세요.
=> 🔀 Feat/myPageFinalUI#269

gongjakso/src/pages/ContestListBox/ContestListBox.Styled.jsx, gongjakso/src/pages/ContestListPage/ContestListPage.jsx, gongjakso/src/pages/DetailPage/DetailPageContest.jsx, gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx, gongjakso/src/router/Router.jsx
#282 UI 수정 및 페이지 연결
1. 전체적인 UI 수정
2. 부족했던 페이지 연결
1. 공모전리스트 부분에서 공모전사진이 비율이 잘 맞게 수정 됐는지 확인해주세요
Issue Number:  #282
=> 🔀 Refactor/editUIandWebOptimization#282 [웹 최적화 및 UI 수정]

gongjakso/src/pages/ProfilePage/ProfilePage.jsx, gongjakso/src/pages/ProfilePage/ProfilePageStyled.jsx, gongjakso/src/pages/ProfileParticipated/ParticipatedTeam.jsx, gongjakso/src/pages/ProfileParticipated/ParticipatedTeamStyled.jsx, gongjakso/src/pages/ProfileRecruited/RecruitedTeam.Styled.jsx, gongjakso/src/pages/ProfileRecruited/RecruitedTeam.jsx, gongjakso/src/pages/ScrapPage/Scrap.Styled.jsx, gongjakso/src/pages/ScrapPage/Scrap.jsx, gongjakso/src/pages/TeamBox/TeamBoxStyled.jsx
#290 마이페이지 반응형 작업
1. 마이페이지 메인 페이지 반응형 작업
2. 000님의 모집/지원/참여 기록 페이지 반응형 작업
3. 000님의 스크랩 페이지 반응형 작업
1. 작업 내역의 다섯 페이지가 모두 반응형 작동이 정상적으로 되는지 확인해주세요
Issue Number:  #290
=> 🔀 Refactor/profilePage#290

gongjakso/src/features/modal/ClickmyApply.jsx, gongjakso/src/pages/DetailPage/DetailPageContest.jsx, gongjakso/src/pages/DetailPage/DetailPageProject.jsx, gongjakso/src/pages/DetailPage/DetailPageStyled.jsx
1. 공고상세페이지 1024 기준 화면 깨지는 부분을 반응형으로 디자인 수정
2. 사용하지 않는 `DetailPageProject` 와 `ClickmyApply` 코드 주석 처리
1. 공고 상세페이지 부분이 1024인 경우 화면이 올바르게 놓여져 있는지 확인해주세요
Issue Number:  #289
=> 🔀 Refactor/DetailPageDesign#289 [공고상세페이지 반응형 및 불필요한 코드 삭제]

gongjakso/src/features/modal/ApplyModal.styled.jsx, gongjakso/src/pages/DetailPage/DetailPageContest.jsx, gongjakso/src/pages/DetailPage/DetailPageStyled.jsx, gongjakso/src/pages/ProfileRecruit/PdfUserApplicationStyled.jsx, gongjakso/src/pages/TeamBox/TeamBoxStyled.jsx
1. 공고 상세페이지 설명글 : 줄바꿈 반영
2. 공고 상세페이지 파란색 박스 크기 조정
3. 팀박스 폰트 크기 1.1rem 으로 수정
4. 지원서 pdf 노션/포트폴리오 보기 버튼 사이즈 조절
1. 공고 상세페이지 설명글에 줄바꿈이 반영되는지 확인해주세요
2. 공고 상세페이지 전체 UI 스타일에 깨지는 부분이 없는지 확인해주세요
3. 팀박스 부분 이름, 날짜 폰트 크기가 적절한지 확인해주세요
Issue Number:  #294
=> 🔀 Fix/DescriptionBox#294 [ 공고상세페이지 줄바꿈 반영 및 박스 사이즈 조절 ]

gongjakso/src/App.js, gongjakso/src/components/Auth/Login.jsx, gongjakso/src/components/Footer/Footer.jsx, gongjakso/src/components/common/Calendar/SelectDate.Styled.jsx, gongjakso/src/components/common/Calendar/SelectDate.jsx, gongjakso/src/components/common/ConfirmModal/ConfirmModal.Styled.jsx, gongjakso/src/components/common/CountGuest/CountGuest.Styled.jsx, gongjakso/src/components/common/CountGuest/CountGuest.jsx, gongjakso/src/components/common/Input/Input.Styled.jsx, gongjakso/src/components/common/Input/Input.jsx, gongjakso/src/features/modal/ApplyModal.styled.jsx, gongjakso/src/features/modal/modalSlice/confirmModalSlice.js, gongjakso/src/naverbdd9e8efc1f0bfbe1818c3673cc9177e.html, gongjakso/src/pages/ContestDetailPage/ContestDetailPage.Styled.jsx, gongjakso/src/pages/ContestListBox/ContestListBox.Styled.jsx, gongjakso/src/pages/ContestListPage/ContestListPage.jsx, gongjakso/src/pages/DetailPage/DetailPageContest.jsx, gongjakso/src/pages/DetailPage/DetailPageStyled.jsx, gongjakso/src/pages/PostMainPage/PostMainPage.Styled.jsx, gongjakso/src/pages/PostMainPage/PostMainPage.jsx, gongjakso/src/pages/ProfilePage/ProfilePage.jsx, gongjakso/src/pages/ProfileRecruit/PdfUserApplicationStyled.jsx, gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx, gongjakso/src/pages/TeamBox/TeamBoxStyled.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.Styled.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.jsx, gongjakso/src/service/post_service.js
공모전 리스트
1. 페이지 네이션 이동 시 랜더링 이슈로 페이지 갇힘 해결
2. 검색 기능 개선
3. 검색 placeholder 통일
4. 검색 입력 시 placeholder 보다 진하게 수정
공고 리스트
1. 정렬, 지역 드롭다운 UI 통일
2. 검색 입력 시 placeholder 보다 진하게 수정
팀빌딩 페이지
1. 캘린더 하나만 띄우는 방식 구현 못함 => 테두리를 만들어서 구분은 확실히 가능하게 구현
2. 취소하기 버튼 클릭 시 "네", "아니오" 모달 생성 => "네" 클릭 시 전페이지로 이동
3. 인원 설정 전 모집 분야 마우스 호버 시 "인원을 먼저 입력해주세요" 문구 생성
4. 온라인/ 오프라인 하나만 선택되게 구현
5. 인원수 업/다운으로 조절하는 기능 제거
위 작업 내역에 적은 내용대로 잘 작동하는지 확인해주세요
Issue Number:  #287
=> 🔀 Refactor/editFeatandUIimprove#287 [공모전 리스트, 공고리스트, 팀빌딩 개선작업]

gongjakso/src/features/modal/SignUpModal.jsx, gongjakso/src/pages/ContestListPage/ContestListPage.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.jsx
1. 회원가입 문구 수정
2. 팀빌딩 온/오프라인 로직 수정
Issue Number:  #299
=> 🔀Refactor/editSignUpandUI [회원가입 UI 수정 및 팀빌딩 로직 수정]

gongjakso/src/features/modal/SignUpModal.jsx, gongjakso/src/pages/ContestListPage/ContestListPage.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.jsx
=> 팀리스트 페이지, 회원가입, 팀빌딩 에러 수정 및 배포

gongjakso/public/_redirects, gongjakso/public/index.html, gongjakso/public/robots.txt
#302 SEO 작업 및 robots.txt 파일 추가 완료
1. robots.txt 파일 추가
2. SEO 작업 및 코드 추가
Issue Number:  #302
=> 🔀 Refactor/addRobotFileandSEOwork#302 [SEO 작업 및 robots.txt 파일 추가] 

gongjakso/src/components/Footer/Footer.Styled.jsx, gongjakso/src/components/Header/Bubble.Styled.jsx, gongjakso/src/components/Header/Buttons.styled.jsx, gongjakso/src/components/Header/Header.Styled.jsx, gongjakso/src/components/common/Calendar/SelectOne.Styled.jsx, gongjakso/src/components/common/Input/Input.Styled.jsx, gongjakso/src/pages/HomePage/HomePage.Styled.jsx, gongjakso/src/pages/HomePage/TopButton.Styled.jsx, gongjakso/src/pages/Portfolio/MakePortfolio.jsx, gongjakso/src/pages/Portfolio/Portfolio.Styled.jsx
1. 메인페이지 px -> rem 변경
2. 포트폴리오 입력/ 사용 페이지 px -> rem 변경
3. input.styled (드롭다운 관련) px -> rem 변경
4. 헤더 및 헤더 버튼 파일 px -> rem 변경
5. 푸터 px -> rem 변경
6. 헤더 마이페이지 아이콘 관련 모달 px -> rem 변경
7. selectone (포트폴리오에 사용되는 캘린더) px -> rem 변경
1. rem으로 통일 후 스타일이 이상하게 변경된 곳이 있는지 확인 부탁드려요
Issue Number:  #306
=> 🔀 Refactor/MainandPortfolioStyle#306 [메인페이지/ 헤더/ 푸터/ 포트폴리오 페이지 스타일 단위 통일]

gongjakso/public/index.html, gongjakso/src/components/common/CountGuest/CountGuest.jsx, gongjakso/src/pages/ProfilePage/ProfilePage.jsx, gongjakso/src/service/portfolio_service.js, gongjakso/src/service/post_service.js, gongjakso/src/service/profile_service.js
1. 토큰이 만료 되면 자동으로 로그아웃되게 구현
2. 메타태그 변경
3. 모집분야 개발자 부분 추가
1. 팀빌딩 모집분야에 개발자 부분이 잘 추가 되었는지 확인해주세요
2. 토큰이 만료되면 로그아웃이 잘 되는지 확인 해주세요 
```
eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5ZW9uODYyMUBuYXZlci5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3MjkwNTM1ODIsImV4cCI6MTcyOTY1ODM4Mn0.sPZDZZcAL-SyiwrP7hOU175II-yfQ3urVxoks3Md640
```
위 만료된 토큰값을 넣고 확인해주세요
Issue Number:  #305
=> 🔀 Refactor/editTokenLogic#305 [토큰 만료시 자동 로그아웃 구현 등]

gongjakso/public/index.html, gongjakso/src/features/modal/ApplyModal.styled.jsx, gongjakso/src/pages/DetailPage/DetailPageContest.jsx, gongjakso/src/pages/DetailPage/DetailPageStyled.jsx
1. 공고 상세페이지 및 지원서 작성 페이지 전체 스타일 단위 `px` 에서 `rem` 으로 수정 완료
2. 공고 상세페이지 메인 타이틀 디자인 수정 반영 완료 (타이틀 양 옆 이미지 제거)
3. `index.html` 파일 수정
4. 전체적인 공고 상세페이지 디자인 크기 조정
공고 상세페이지 및 지원서 작성 부분의 스타일이 깨지지 않는지 확인 부탁드려요!
Issue Number:  #313
=> 🔀 Refactor/DetailAndApplyPageStyleUnit#313 [공고상세페이지 및 지원서 작성 스타일 단위 rem 통일]

gongjakso/public/index.html
=> 링크 공유 시 미리보기 화면 수정 후 배포 2

gongjakso/src/pages/HomePage/HomePage.jsx
=> :pencil2: Edit MetaTag

gongjakso/src/components/common/Input/infoDrop.styled.jsx, gongjakso/src/pages/ProfileApplied/AppliedTeamStyled.jsx, gongjakso/src/pages/ProfileInfo/MyInfoStyled.jsx, gongjakso/src/pages/ProfilePage/ProfilePage.jsx, gongjakso/src/pages/ProfilePage/ProfilePageStyled.jsx, gongjakso/src/pages/ProfileParticipated/ParticipatedTeamStyled.jsx, gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx, gongjakso/src/pages/ProfileRecruit/ProfileRecruit.styled.jsx, gongjakso/src/pages/ProfileRecruited/RecruitedTeam.Styled.jsx, gongjakso/src/pages/ScrapPage/Scrap.Styled.jsx, gongjakso/src/pages/TeamBox/TeamBoxStyled.jsx
1. 마이페이지 스타일 rem 변환
2. 정보 수정 페이지 스타일 rem 변환
3. 모집 중인 공고 페이지 스타일 rem 변환
4. 모집 기록 페이지 스타일 rem 변환
5. 지원 기록 페이지 스타일 rem 변환
6. 참여 기록 페이지 스타일 rem 변환
위 작업 내역의 총 6개 페이지 중 스타일이 깨지는 것이 있는지 확인해 주세요.
Issue Number:  #319
=> 🔀 Refactor/myPageStyle#319 [마이페이지 전체 스타일 rem 변환]

gongjakso/src/components/Footer/Footer.Styled.jsx, gongjakso/src/components/Footer/Footer.jsx, gongjakso/src/components/Header/Bubble.Styled.jsx, gongjakso/src/components/Header/Buttons.styled.jsx, gongjakso/src/components/Header/Header.Styled.jsx, gongjakso/src/styles/theme.js
#337 헤더와 푸터 반응형 작업 완료
1. 헤더와 푸터가 반응형이 잘 진행 되었는지 확인해주세요
2. 이전 머지했던 부분들이 같이 잘 적용되었는지 확인해주세요
1. 푸터 같은 경우 사이즈가 줄어들면 서비스 소개와 카피라이트 부분이 사라지는게 정상입니다.
Issue Number:  #337
=> Refactor/ResponsiveContestListPage#337 [헤더와 푸터 반응형 작업]

gongjakso/src/components/common/Input/infoDrop.styled.jsx, gongjakso/src/features/modal/ApplyCancel.jsx, gongjakso/src/features/modal/ApplyModal.styled.jsx, gongjakso/src/features/modal/Completed.jsx, gongjakso/src/pages/DetailPage/DetailPageContest.jsx, gongjakso/src/pages/DetailPage/DetailPageStyled.jsx, gongjakso/src/pages/ProfileApplied/AppliedTeamStyled.jsx, gongjakso/src/pages/ProfileInfo/MyInfo.jsx, gongjakso/src/pages/ProfileInfo/MyInfoStyled.jsx, gongjakso/src/pages/ProfilePage/ProfilePageStyled.jsx, gongjakso/src/pages/ProfileParticipated/ParticipatedTeamStyled.jsx, gongjakso/src/pages/ProfileRecruit/PdfUserApplicationStyled.jsx, gongjakso/src/pages/ProfileRecruit/ProfileRecruit.styled.jsx, gongjakso/src/pages/ProfileRecruited/RecruitedTeam.Styled.jsx, gongjakso/src/pages/ScrapPage/Scrap.Styled.jsx, gongjakso/src/pages/TeamBox/TeamBox.jsx, gongjakso/src/pages/TeamBox/TeamBoxStyled.jsx
1. 팀박스 반응형 UI 구현
2. 내의 00기록 페이지 반응형 UI 구현
3. 나의 정보 반응형 UI 구현
4. 프로필페이지 반응형 UI 구현
작업 내역에 있는(아래 4개) 페이지의 반응형 UI가 정상 작동되는지 확인 부탁드립니다.
1. 팀박스
2. 내의 00기록 (3개) + 스크랩
3. 나의 정보
4. 프로필 메인 페이지
1. 내가 모집 중인 팀 상세페이지의 경우 반응형 UI 수정이 아직 진행 중입니다..
Issue Number:  #331
=> 🔀 Refactor/myPageMobile#331

gongjakso/src/components/Auth/Login.Styled.jsx
#332 로그인 페이지 margin 추가
- 로그인 페이지 헤더 마진 추가
- 로그인 페이지 헤더가 잘 눌리는지 확인해주세요
Issue Number:  #332
=> 🔀 Fix LoginPage

gongjakso/src/components/SwiperBanner/SwiperBanner.Styled.jsx, gongjakso/src/components/SwiperBanner/SwiperBanner.jsx, gongjakso/src/components/common/CountGuest/CountGuest.Styled.jsx, gongjakso/src/components/common/Input/Input.Styled.jsx, gongjakso/src/components/common/Input/Multilevel.styled.jsx, gongjakso/src/features/NoContents/NoContents.styled.jsx, gongjakso/src/pages/ContestDetailPage/ContestDetailPage.Styled.jsx, gongjakso/src/pages/ContestDetailPage/ContestDetailPage.jsx, gongjakso/src/pages/ContestListBox/ContestListBox.Styled.jsx, gongjakso/src/pages/PostMainPage/PostMainPage.Styled.jsx, gongjakso/src/pages/PostMainPage/PostMainPage.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.Styled.jsx, gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.jsx
#339 반응형 UI 구현 및 수정
1. 공모전리스트 페이지 반응형 구현
2. 팀빌딩페이지 반응형 구현
Issue Number:  #339
=> 🔀 공모전리스트, 팀빌딩페이지 반응형 UI 구현 및 수정

gongjakso/src/components/common/Input/infoDrop.styled.jsx, gongjakso/src/pages/ProfileInfo/MyInfo.jsx, gongjakso/src/pages/ProfileInfo/MyInfoStyled.jsx
- 마이페이지 '나의 정보' 반응형 스타일 수정
- '나의 정보' 전체 드롭다운 반응형 크기 수정
Issue Number: #346
=> fix/myInfoDropdown [ 나의 정보 반응형 ]

gongjakso/src/pages/ProfilePage/ProfilePage.jsx, gongjakso/src/pages/ProfilePage/ProfilePageStyled.jsx, gongjakso/src/pages/ProfileRecruit/ProfileRecruit.styled.jsx, gongjakso/src/pages/TeamBox/TeamBox.jsx, gongjakso/src/pages/TeamBox/TeamBoxStyled.jsx
1. 프로필 메인페이지 - 상단 나의 정보 부분 반응형 UI 구현
2. 내가 모집 중인 팀 상세페이지 반응형 UI 구현
1. 프로필 메인페이지 상단 나의 정보 부분이 반응형에 따라 잘 작동되는지 확인해주세요.
2. 내가 모집 중인 팀(모집 기록X) 반응형 UI가 잘 작동되는지 확인해주세요.
Issue Number:  #331
=> 🔀Refactor/myPageMobile#331
